import 'reflect-metadata';
import { NestFactory } from '@nestjs/core';
import { ValidationPipe, ClassSerializerInterceptor } from '@nestjs/common';
import { Reflector } from '@nestjs/core';
import { RequestLoggerInterceptor } from './core/middleware/request-logger.interceptor';
import { AppModule } from './app';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  // Enable CORS so the frontend (e.g. Angular dev server on localhost:4200)
  // can perform requests including preflight (OPTIONS).
  // Adjust CORS_ORIGIN in production as needed.
  app.enableCors({
    origin: process.env.CORS_ORIGIN || 'http://localhost:4200',
    methods: 'GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS',
    allowedHeaders: 'Content-Type, Authorization',
    credentials: true,
  });

  app.setGlobalPrefix('api');
  app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true }));
  app.useGlobalInterceptors(new RequestLoggerInterceptor(), new ClassSerializerInterceptor(app.get(Reflector)));

  const PORT = process.env.PORT || 3333;
    // Swagger (autogenerated via decorators)
    const config = new DocumentBuilder()
      .setTitle('LIA API')
      .setDescription('API documentation for LIA project')
      .setVersion('1.0')
      .addBearerAuth({ type: 'http', scheme: 'bearer', bearerFormat: 'JWT' }, 'JWT')
      .build();

    const document = SwaggerModule.createDocument(app, config);
    SwaggerModule.setup('api/docs', app, document);
  await app.listen(PORT);
  console.log(`🚀 Nest server running on port ${PORT}`);
}

bootstrap();
